baseURL = "https://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[taxonomies]
tag = "tags"
category = "categories"
[permalinks]
  projects = "/projects/"
  others = "/others/"
  work = "/work/"
