baseURL = "https://safelg.com"
languageCode = "en-us"
title = "portfolio"

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"
category = "categories"
[permalinks]
  projects = "/projects/"
  others = "/others/"
  work = "/work/"
